import { Register } from '../../types';

export const REGISTERS: Register.Queries = new Map([

  /* Input registers */

  [ 'Bus.Version', {
    addr: 0,
    type: Register.Type.Input,
    description: 'Protocol version number',
  }],
  [ 'App.VersionMajor', {
    addr: 1,
    type: Register.Type.Input,
    description: 'Software version - major (2 character ascii text)',
  }],
  [ 'App.VersionMinor', {
    addr: 2,
    type: Register.Type.Input,
    description: 'Software version - minor (2 character ascii text)',
  }],
  [ 'App.VersionRelease', {
    addr: 3,
    type: Register.Type.Input,
    description: 'Software version - release (2 character ascii text)',
  }],
  [ 'Input.AirFilter', {
    addr: 101,
    type: Register.Type.Input,
    description: 'Air filter alarm',
  }],
  [ 'Input.T0_Controller', {
    addr: 200,
    type: Register.Type.Input,
    description: 'Controller board temperature',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T1_Intake', {
    addr: 201,
    type: Register.Type.Input,
    description: 'Fresh air intake temperature',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T2_Inlet', {
    addr: 202,
    type: Register.Type.Input,
    description: 'Inlet temperature (before heater)',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T3_Exhaust', {
    addr: 203,
    type: Register.Type.Input,
    description: 'Room exhaust temperature',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T4_Outlet', {
    addr: 204,
    type: Register.Type.Input,
    description: 'Outlet temperature',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T5_Cond', {
    addr: 205,
    type: Register.Type.Input,
    description: 'Condenser temperature',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T6_Evap', {
    addr: 206,
    type: Register.Type.Input,
    description: 'Evaporator temperature',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T7_Inlet', {
    addr: 207,
    type: Register.Type.Input,
    description: 'Inlet temperature (after heater)',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T8_Outdoor', {
    addr: 208,
    type: Register.Type.Input,
    description: 'Outdoor temperature',
    scale: 100,
    min: -5000,
    max: 8000,
  }],
  [ 'Input.T9_Heater', {
    addr: 209,
    type: Register.Type.Input,
    description: 'Heating surface temperature',
    scale: 100,
    min: -5000,
    max: 8000,
  }],
  [ 'Input.T10_Extern', {
    addr: 210,
    type: Register.Type.Input,
    description: 'External room temperature',
    scale: 100,
    min: -5000,
    max: 8000,
  }],
  [ 'Input.T11_Top', {
    addr: 211,
    type: Register.Type.Input,
    description: 'Hot water top temperature',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T12_Bottom', {
    addr: 212,
    type: Register.Type.Input,
    description: 'Hot water bottom temperature',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T13_Return', {
    addr: 213,
    type: Register.Type.Input,
    description: 'EK return temperature',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T14_Supply', {
    addr: 214,
    type: Register.Type.Input,
    description: 'EK supply temperature',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T15_Room', { 
    addr: 215,
    type: Register.Type.Input,
    description: 'User panel room temperature',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.T16', {
    addr: 216,
    type: Register.Type.Input,
    description: 'AUX temperature (sacrificial anode)',
    scale: 100,
    min: 0,
    max: 7000,
  }],
  [ 'Input.RH', {
    addr: 221,
    type: Register.Type.Input,
    description: 'Humidity',
    scale: 100,
    min: 0,
    max: 10000,
  }],
  [ 'Input.CO2', { 
    addr: 222,
    type: Register.Type.Input,
    description: 'Carbon dioxide',
    min: 0,
    max: 40000,
  }],
  [ 'Alarm.Status', {
    addr: 400,
    type: Register.Type.Input,
    description: 'Alarm state bit mask, 0x80 = Active, 0x03 = number of alarms',
  }],
  [ 'Alarm.List_1_ID', {
    addr: 401,
    type: Register.Type.Input,
    description: 'Alarm 1 code',
  }],
  [ 'Alarm.List_2_ID', {
    addr: 404,
    type: Register.Type.Input,
    description: 'Alarm 2 code',
  }],
  [ 'Alarm.List_3_ID', {
    addr: 407,
    type: Register.Type.Input,
    description: 'Alarm 3 code',
  }],
  [ 'Control.RunAct', {
    addr: 1000,
    type: Register.Type.Input,
    description: 'Actual on/off state',
    min: 0,
    max: 1,
  }],
  [ 'Control.ModeAct', {
    addr: 1001,
    type: Register.Type.Input,  
    description: 'Actual operation mode',
    min: 0,
    max: 4,
  }],
  [ 'Control.State', {
    addr: 1002,
    type: Register.Type.Input,
    description: 'Actual control state',
    min: 0,
    max: 16,
  }],
  [ 'AirFlow.SinceFiltDay', {
    addr: 1103,
    type: Register.Type.Input,
    description: 'Days since last air filter change alarm',
  }],
  [ 'AirFlow.ToFiltDay', {
    addr: 1104,
    type: Register.Type.Input,
    description: 'Days to next air filter change alarm',
  }],
  [ 'AirTemp.IsSummer', {
    addr: 1200,
    type: Register.Type.Input,
    description: 'Summer state',
    min: 0,
    max: 1,
  }],
  [ 'AirTemp.TempInlet', {
    addr: 1201,
    type: Register.Type.Input,
    description: 'Inlet temperature request (T7 setpoint)',
    scale: 100,
    min: -5000,
    max: 8000,
  }],
  [ 'AirTemp.TempControl', {
    addr: 1202,
    type: Register.Type.Input,
    description: 'Actual value for controlled temperature',
    scale: 100,
    min: -5000,
    max: 8000,
  }],
  [ 'AirTemp.TempRoom', {
    addr: 1203,
    type: Register.Type.Input,
    description: 'Actual room temperature',
    scale: 100,
    min: -5000,
    max: 8000,
  }],
  [ 'AirTemp.EffPct', {
    addr: 1204,
    type: Register.Type.Input,
    description: 'Passive heat exchanger efficiency',
    scale: 100,
    min: -5000,
    max: 8000,
  }],
  [ 'AirTemp.CapSet', {
    addr: 1205,
    type: Register.Type.Input,
    description: 'Requested capacity',
    scale: 100,
    min: 0,
    max: 10000,
  }],
  [ 'AirTemp.CapAct', {
    addr: 1206,
    type: Register.Type.Input,
    description: 'Actual capacity',
    scale: 100,
    min: 0,
    max: 10000,
  }],
  [ 'AirQual.CO2_Enable', { // Not known if works..
    addr: 3003,
    type: Register.Type.Input,
    description: 'Return > 0 if CO2 sensor is present, otherwise 0 or fail register reading',
  }],

  /* Holding registers */

  [ 'Output.ExhaustSpeed', {
     addr: 200,
     type: Register.Type.Holding,
     description: 'Exhaust fan speed',
     scale: 100,
     min: 100,
     max: 10000,
  }],
  [ 'Output.InletSpeed', {
     addr: 201,
     type: Register.Type.Holding,
     description: 'Inlet fan speed',
     scale: 100,
     min: 100,
     max: 10000,
  }],
  [ 'Output.AirHeatCap', {
     addr: 202,
     type: Register.Type.Holding,
     description: 'Air heater capacity',
     scale: 100,
     min: 100,
     max: 10000,
  }],
  [ 'Output.CenHeatCap', {
     addr: 203,
     type: Register.Type.Holding,
     description: 'Central heater capacity',
     scale: 100,
     min: 100,
     max: 10000,
  }],
  [ 'Output.CprCap', {
     addr: 204,
     type: Register.Type.Holding,
     description: 'Compresor capacity',
     scale: 100,
     min: 100,
     max: 10000,
  }],
  [ 'Output.EarthSpeed', {
     addr: 205,
     type: Register.Type.Holding,
     description: 'Earth tube air intake fan speed',
     scale: 100,
     min: 100,
     max: 10000,
  }],
  [ 'Program.UserFuncAct', {
    addr: 600,
    type: Register.Type.Holding,
    description: 'User function active',
    min: 0,
    max: 6,
  }],
  [ 'Program.UserFuncSet', {
    addr: 601,
    type: Register.Type.Holding,
    description: 'User function select',
    min: 0,
    max: 6,
  }],
  [ 'Program.UserTimeSet', {
    addr: 602,
    type: Register.Type.Holding,
    description: 'User function period',
    min: 0,
    max: 120,
  }],
  [ 'Control.Type', {
     addr: 1000,
     type: Register.Type.Holding,
     description: 'Machine type select (DO NOT WRITE TO THIS)',
     min: 0,
     max: 255,
  }],
  [ 'Control.RunSet', {
    addr: 1001,
    type: Register.Type.Holding,
    description: 'User on/off select',
    min: 0,
    max: 1,
  }],
  [ 'Control.ModeSet', {
    addr: 1002,
    type: Register.Type.Holding,
    description: 'User operation mode select',
    min: 0,
    max: 4,
  }],
  [ 'Control.VentSet', {
    addr: 1003,
    type: Register.Type.Holding,
    description: 'User ventilation step select',
    min: 0,
    max: 4,
  }],
  [ 'Control.TempSet', { 
    addr: 1004,
    type: Register.Type.Holding,
    description: 'User temperature setpoint',
    scale: 100,
    min: 500,  
    max: 3000, 
  }],
  [ 'Control.ServiceMode', {
    addr: 1005,
    type: Register.Type.Holding,
    description: 'Service mode select',
    scale: 1,
    min: 0,
    max: 8,
  }],
  [ 'Control.ServicePct', {
    addr: 1006,
    type: Register.Type.Holding,
    description: 'Service mode capacity',
    scale: 100,
    min: 100,
    max: 10000,
  }],
  [ 'Control.Preset', {
    addr: 1007,
    type: Register.Type.Holding,
    description: 'Request preset to factory settings',
    scale: 1,
    min: 0,
    max: 3,
  }],
  [ 'AirFlow.AirExchMode', { 
    addr: 1100,
    type: Register.Type.Holding,
    description: 'Air exchange mode',
    scale: 1,
    min: 0,
    max: 2,
  }],
  [ 'HotWater.TempSet_T11', {
    addr: 1700,
    type: Register.Type.Holding,
    description: 'Top temperature setpoint',
    scale: 100,
    min: 500,
    max: 6500,
  }],
  [ 'HotWater.TempSet_T12', {
    addr: 1701,
    type: Register.Type.Holding,
    description: 'Bottom temperature setpoint',
    scale: 100,
    min: 500, 
    max: 6500,
  }],
  [ 'CentralHeat.HeatExtern', { 
    addr: 1800,
    type: Register.Type.Holding,
    description: 'External heating offset from room temperature setpoing',
    scale: 100,
    min: 500,
    max: 6500,
  }],
  [ 'AirQual.RH_VentLo', {
    addr: 1910,
    type: Register.Type.Holding,
    description: 'AirQual.RH_VentLo 1910 Step Humidity low winter step select',
    scale: 1,
  }],
  [ 'AirQual.RH_VentHi', {
    addr: 1911,
    type: Register.Type.Holding,
    description: 'Humidity high step select',
    scale: 1,
  }],
  [ 'AirQual.RH_LimLo', {
    addr: 1912,
    type: Register.Type.Holding,
    description: 'Humidity limit for low ventilation',
    scale: 100,
    min: 0,
    max: 10000,
  }],
  [ 'AirQual.RH_Timeout', {
    addr: 1913,
    type: Register.Type.Holding,
    description: 'Humidity max. time on high ventilation',
    scale: 1,
  }],
  [ 'Control.PowerSave', {
    addr: 4041,
    type: Register.Type.Holding,
    description: 'Enable power saving features',
    scale: 1,
    min: 0,
    max: 1,
  }],
]);
